# Latexmk script for generating FIDATA Report Template
# Copyright (C) 2014  Basil Peace
# 
# This file is part of FIDATA Report Template.
# 
# FIDATA Report Template is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# FIDATA Report Template is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with FIDATA Report Template.  If not, see
# <http://www.gnu.org/licenses/>.

# The following external artifacts should be placed in this directory
# before build:
# 	fonts subdirectory

$pdflatex = "lualatex %O %S";
$pdf_mode = 1; $postscript_mode = $dvi_mode = 0;
$bibtex_use = 1;
$makeindex = "makeindex -s gind.ist %S";
$clean_ext = "bbl glo brf";
$clean_full_ext = "cls";
@default_files = ("fidata-report-template.dtx", "example.tex");
